import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

export type Language = 'en' | 'id' | 'zh';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const translations: Record<Language, Record<string, string>> = {
  en: {
    // Header
    'nav.home': 'Home',
    'nav.about': 'About',
    'nav.projects': 'Projects',
    'nav.whyIndonesia': 'Why Indonesia',
    'nav.howItWorks': 'How It Works',
    'nav.contact': 'Contact',
    
    // Footer
    'footer.description': 'A transparent approach to cross-border real estate investment in Indonesia\'s most resilient lifestyle destinations.',
    'footer.navigation': 'Navigation',
    'footer.information': 'Information',
    'footer.legalStructures': 'Legal Structures',
    'footer.risksDisclaimers': 'Risks & Disclaimers',
    'footer.faqs': 'FAQs',
    'footer.allRightsReserved': 'All rights reserved.',
    'footer.baliIndonesia': 'Bali, Indonesia',
    'footer.language': 'Language',
    
    // Index Page
    'index.hero.title': 'Invest in Bali\'s Best-Performing Property Market',
    'index.hero.subtitle': 'Wahi offers international investors access to high-yield, professionally managed real estate in Southeast Asia\'s most dynamic tourism destination.',
    'index.hero.bookConsultation': 'Book a Consultation',
    'index.hero.exploreProjects': 'Explore Projects',
    'index.invest.title': 'Invest Beyond Low-Yield Markets',
    'index.invest.description1': 'Many international investors find that property at home no longer delivers meaningful income. With high prices and net yields often below 3%, residential real estate has become a store of capital rather than a source of growth.',
    'index.invest.description2': 'Indonesia — and Bali in particular — offers an alternative. A combination of strong tourism demand, limited quality supply, and significantly lower entry prices creates an opportunity for yields of 8–12% or more.',
    'index.invest.description3': 'Wahi identifies and develops lifestyle properties in locations with year-round occupancy and long-term appreciation potential. Our projects are designed for investors who want income, not just ownership.',
    'index.pillars.title': 'Three Pillars of Smart Investment',
    'index.pillars.quote': '"We help investors access the returns that their own markets no longer provide."',
    'index.pillars.location': 'Location',
    'index.pillars.locationDesc': 'Bali leads Southeast Asia in tourism recovery and lifestyle demand.',
    'index.pillars.design': 'Design',
    'index.pillars.designDesc': 'Thoughtful architecture that commands premium rental rates.',
    'index.pillars.structure': 'Structure',
    'index.pillars.structureDesc': 'Clear, legal, and professionally managed investments.',
    'index.featured.title': 'Featured Projects',
    'index.featured.viewAll': 'View All Projects',
    'index.whyBali.title': 'Why Bali?',
    'index.whyBali.demand': 'Demand',
    'index.whyBali.demandDesc': 'Over 6.3 million international visitors in 2024, with strong growth projected.',
    'index.whyBali.supply': 'Supply',
    'index.whyBali.supplyDesc': 'Limited land and strict building codes protect property values.',
    'index.whyBali.returns': 'Returns',
    'index.whyBali.returnsDesc': 'Net rental yields of 8–12% are achievable in prime locations.',
    'index.whyBali.learnMore': 'Learn More About Indonesia',
    'index.cta.title': 'Ready to Start?',
    'index.cta.description': 'Book a no-obligation consultation with a local Wahi representative.',
    'index.cta.button': 'Book a Consultation',
    
    // Projects Page
    'projects.hero.title': 'Real Projects. Real Demand. Real Returns.',
    'projects.hero.description': 'Wahi develops high-quality properties in locations with strong tourism fundamentals and year-round occupancy potential. Each project is designed, built, and structured to perform as a long-term investment.',
    'projects.available': 'Available',
    'projects.enquireNow': 'Enquire Now',
    'projects.cta.title': 'Not Sure Which Project Fits You Best?',
    'projects.cta.description': 'Speak with a Wahi advisor to compare options and opportunities.',
    'projects.cta.button': 'Schedule a Consultation',
    
    // About Page
    'about.hero.title': 'Property Development with Clarity, Not Complexity',
    'about.hero.description': 'Wahi is a boutique property development and investment firm based in Bali, Indonesia. We work with international investors who want clear, transparent access to Southeast Asian real estate — without hidden structures, unclear contracts, or language barriers.',
    'about.whoWeAre.title': 'Who We Are',
    'about.whoWeAre.description1': 'Wahi was founded with a single goal: to make Indonesian property investment accessible, understandable, and rewarding for international investors.',
    'about.whoWeAre.description2': 'Our team combines deep local expertise with a global perspective. We manage every step of the process — from site selection and development to sales, legal structuring, and property management — so that investors can participate with confidence.',
    'about.whatWeDo.title': 'What We Do',
    'about.whatWeDo.description': 'Wahi develops and curates real estate projects in Bali and selected Indonesian locations. We focus on:',
    'about.whatWeDo.item1': 'Lifestyle properties in high-demand areas',
    'about.whatWeDo.item2': 'Hospitality-grade design and finishes',
    'about.whatWeDo.item3': 'Clear ownership structures for foreign buyers',
    'about.whatWeDo.item4': 'Professional rental and property management',
    'about.whatWeDo.closing': 'Each project is designed to generate rental income while offering long-term capital appreciation.',
    'about.whyReliable.title': 'Why Wahi is a Reliable Partner',
    'about.whyReliable.item1': 'Local presence in Bali with regional offices in key markets',
    'about.whyReliable.item2': 'End-to-end involvement — we develop, sell, and manage',
    'about.whyReliable.item3': 'Direct relationships with notaries, legal advisors, and banks',
    'about.whyReliable.item4': 'Transparent pricing and clear documentation',
    'about.whyReliable.item5': 'Track record in hospitality and property investment',
    'about.localOffice.title': 'The Role of the Local Office in [COUNTRY]',
    'about.localOffice.intro': 'Wahi [COUNTRY] is your local point of contact for Indonesian property investment.',
    'about.localOffice.purpose': 'The purpose of the regional office is to make cross-border investing simple, clear, and comfortable for investors based in [COUNTRY].',
    'about.localOffice.provides': 'The local representative provides:',
    'about.localOffice.item1': 'Personal consultations in your language and time zone',
    'about.localOffice.item2': 'Clear explanations of Indonesian property structures',
    'about.localOffice.item3': 'Guidance on legal and financial considerations',
    'about.localOffice.item4': 'Coordination with local real estate agents',
    'about.localOffice.item5': 'Assistance throughout the buying process',
    'about.localOffice.item6': 'Ongoing support after purchase',
    'about.localOffice.closing': 'Rather than dealing with an overseas developer directly, you have a knowledgeable local advisor who understands both the Indonesian market and the expectations of investors from [COUNTRY].',
    'about.investorProcess.title': 'How We Work with Investors',
    'about.investorProcess.item1': 'Initial consultation to understand goals and budget',
    'about.investorProcess.item2': 'Presentation of suitable projects and units',
    'about.investorProcess.item3': 'Clear explanation of legal structures and costs',
    'about.investorProcess.item4': 'Support through documentation and payment',
    'about.investorProcess.item5': 'Coordination with legal and financial professionals',
    'about.investorProcess.item6': 'Ongoing communication through construction and handover',
    'about.investorProcess.item7': 'Rental onboarding and property management',
    'about.investorProcess.closing': 'At every stage, the local Wahi representative remains your primary contact, while the Indonesian team handles project delivery and operations.',
    'about.longTerm.title': 'A Long-Term Approach',
    'about.longTerm.item1': 'Fair, market-aligned pricing',
    'about.longTerm.item2': 'Sustainable, quality-focused design',
    'about.longTerm.item3': 'Repeat investor relationships',
    'about.longTerm.item4': 'Honest guidance, even when the answer is "no"',
    'about.longTerm.closing': 'Our business depends on trust — and we earn it through transparency, consistency, and results.',
    'about.cta.title': 'Ready to Talk?',
    'about.cta.description': 'Book a consultation to learn how Wahi can help you invest in Indonesian property.',
    'about.cta.button': 'Book a Consultation',
    
    // Why Invest Page
    'whyInvest.hero.title': 'Why Invest in Indonesia?',
    'whyInvest.hero.description': 'For investors from [COUNTRY], property markets at home often deliver modest returns. Indonesia offers a different profile: a fast-growing economy, globally recognized destinations, and year-round tourism demand that supports significantly higher rental yields.\n\nThis page explains, in practical terms, why Indonesia — and Bali in particular — has become one of the most attractive property investment markets in Asia.',
    'whyInvest.demand.title': 'More Demand Than Quality Supply',
    'whyInvest.demand.description': 'Bali remains one of Southeast Asia\'s most desirable destinations. Following the pandemic, international arrivals have rebounded sharply — and the demand for high-quality accommodation continues to outpace supply.',
    'whyInvest.demand.item1': '6.3 million+ international visitors to Bali in 2024',
    'whyInvest.demand.item2': 'Strong digital nomad and lifestyle traveler presence',
    'whyInvest.demand.item3': 'Limited quality inventory in premium locations',
    'whyInvest.demand.item4': 'Year-round tourism with minimal seasonal dips',
    'whyInvest.demand.closing': 'For investors, this imbalance between demand and supply supports:',
    'whyInvest.demand.benefit1': 'strong occupancy',
    'whyInvest.demand.benefit2': 'competitive nightly rates',
    'whyInvest.demand.benefit3': 'long-term value appreciation',
    'whyInvest.prices.title': 'Lower Prices, Higher Income',
    'whyInvest.prices.description': 'Compared to major cities in [COUNTRY], Bali offers significantly lower entry prices for comparable quality.',
    'whyInvest.prices.item1': 'Premium villas from USD 250,000–500,000',
    'whyInvest.prices.item2': 'Net rental yields of 8–12% achievable',
    'whyInvest.prices.item3': 'Capital appreciation of 5–10% annually in select areas',
    'whyInvest.prices.closing': 'This combination of lower cost and higher yield creates opportunities rarely available in more developed markets.',
    'whyInvest.growth.title': 'Backed by Long-Term Economic Growth',
    'whyInvest.growth.description': 'Indonesia is Southeast Asia\'s largest economy, with:',
    'whyInvest.growth.item1': 'Population of 275 million+',
    'whyInvest.growth.item2': 'Consistent GDP growth above 5% annually',
    'whyInvest.growth.item3': 'Government investment in infrastructure and tourism',
    'whyInvest.growth.item4': 'Stable legal environment for property ownership',
    'whyInvest.growth.closing': 'Tourism remains a strategic national industry, with ongoing investment into airports, roads, and services—strengthening the long-term outlook for property owners.',
    'whyInvest.diversification.title': 'Portfolio Diversification Benefits',
    'whyInvest.diversification.description': 'For international investors, Indonesian property offers:',
    'whyInvest.diversification.item1': 'Exposure to emerging market growth',
    'whyInvest.diversification.item2': 'Assets outside of [COUNTRY] property trends',
    'whyInvest.diversification.item3': 'USD-denominated income in many cases',
    'whyInvest.diversification.item4': 'Lifestyle value as a secondary benefit',
    'whyInvest.alternative.title': 'A Compelling Alternative to Low-Yield Markets',
    'whyInvest.alternative.description': 'For investors in [COUNTRY] facing high prices and low returns at home, Indonesia offers a rare combination of:',
    'whyInvest.alternative.item1': 'Affordable entry points',
    'whyInvest.alternative.item2': 'Strong rental demand',
    'whyInvest.alternative.item3': 'Professional management infrastructure',
    'whyInvest.alternative.item4': 'Legal structures designed for foreign ownership',
    'whyInvest.alternative.closing': 'With the right project and the right partner, Indonesian property can become a powerful addition to a diversified investment portfolio.',
    'whyInvest.cta.title': 'Start Exploring',
    'whyInvest.cta.description': 'If you\'re considering Indonesia as part of your investment strategy, we\'re here to help.',
    'whyInvest.cta.button': 'View Current Developments',
    
    // How It Works Page
    'howItWorks.hero.title': 'Buying Property in Bali – Clear, Legal, and Structured',
    'howItWorks.hero.description': 'Investing in Indonesian real estate is straightforward when it is approached with the right structure and professional guidance. This page explains – in practical terms – how foreign investors purchase, own, and earn income from property developed by Wahi. Our goal is to remove uncertainty and provide a transparent, step-by-step framework from first enquiry to completed ownership.',
    'howItWorks.hakSewa.title': 'The Most Common Model: Hak Sewa (Leasehold)',
    'howItWorks.hakSewa.description': 'Wahi projects for international buyers are primarily structured using Hak Sewa – long-term leasehold ownership. This is the standard and most practical way for foreigners to own property in Indonesia.',
    'howItWorks.hakSewa.terms': 'Typical terms:',
    'howItWorks.hakSewa.item1': 'Initial lease period: around 25–30 years',
    'howItWorks.hakSewa.item2': 'Contractually guaranteed right to extend',
    'howItWorks.hakSewa.item3': 'Full legal control of the unit during the lease',
    'howItWorks.hakSewa.item4': 'Right to rent, resell, or transfer the property',
    'howItWorks.hakSewa.item5': 'Leasehold is widely used across Bali and Indonesia for villas, apartments, and resort residences and is recognized as a secure and bankable structure',
    'howItWorks.misconception.title': 'A Common Misconception About Extensions',
    'howItWorks.misconception.description': 'Many first-time buyers worry that extending a lease means "buying the whole property again." This is not the case. When a lease is extended, the owner normally pays only for:',
    'howItWorks.misconception.item1': 'The value of the land portion',
    'howItWorks.misconception.item2': 'Not for the building itself',
    'howItWorks.misconception.example': 'Example',
    'howItWorks.misconception.exampleLine1': 'Purchase price of a unit: USD 300,000',
    'howItWorks.misconception.exampleLine2': 'Building value: majority of the price',
    'howItWorks.misconception.exampleLine3': 'Land value: a smaller component',
    'howItWorks.misconception.exampleNote': 'At the time of extension, the cost is typically only 10–20% of the original purchase price, depending on the project and land values at that time.',
    'howItWorks.misconception.closing': 'This makes long-term ownership both predictable and economically reasonable.',
    'howItWorks.process.title': 'From First Contact to Ownership',
    'howItWorks.process.subtitle': 'Step-by-Step Process',
    'howItWorks.process.step1.title': 'Initial Consultation',
    'howItWorks.process.step1.description': 'Discussion of your objectives, budget, and preferred project.',
    'howItWorks.process.step2.title': 'Project Selection',
    'howItWorks.process.step2.description': 'Review available units, pricing, and expected timelines.',
    'howItWorks.process.step3.title': 'Reservation',
    'howItWorks.process.step3.description': 'A small booking deposit secures the chosen unit.',
    'howItWorks.process.step4.title': 'Legal Documentation',
    'howItWorks.process.step4.description': 'Formal sales agreement and leasehold contract prepared by notaries and legal professionals.',
    'howItWorks.process.step5.title': 'Payment Milestones',
    'howItWorks.process.step5.description': 'Payments are linked to construction stages or agreed schedules.',
    'howItWorks.process.step6.title': 'Construction & Updates',
    'howItWorks.process.step6.description': 'Regular progress reports and site updates.',
    'howItWorks.process.step7.title': 'Handover',
    'howItWorks.process.step7.description': 'Unit completion, furnishing (if applicable), and final documentation.',
    'howItWorks.process.step8.title': 'Rental Onboarding',
    'howItWorks.process.step8.description': 'Property management setup and income generation begin.',
    'howItWorks.rental.title': 'Rental Income & Management',
    'howItWorks.rental.description': 'Most Wahi buyers are overseas investors who want a completely hands-off experience. Each project is designed with professional operations in mind:',
    'howItWorks.rental.item1': 'On-site management teams',
    'howItWorks.rental.item2': 'Marketing and bookings',
    'howItWorks.rental.item3': 'Maintenance and reporting',
    'howItWorks.rental.item4': 'Transparent financial statements',
    'howItWorks.rental.optionsIntro': 'Owners can typically choose between:',
    'howItWorks.rental.option1': 'Pure investment use',
    'howItWorks.rental.option2': 'Partial personal use with rental income',
    'howItWorks.rental.option3': 'Long-term leasing strategies',
    'howItWorks.rental.closing': 'All details are explained clearly before purchase so expectations remain realistic and aligned.',
    'howItWorks.legal.title': 'Legal and Financial Transparency',
    'howItWorks.legal.intro': 'Wahi works only with:',
    'howItWorks.legal.item1': 'Licensed Indonesian notaries',
    'howItWorks.legal.item2': 'Reputable legal advisors',
    'howItWorks.legal.item3': 'Established property management partners',
    'howItWorks.legal.docsIntro': 'Every step is documented, and investors receive clear explanations of:',
    'howItWorks.legal.doc1': 'Ownership rights',
    'howItWorks.legal.doc2': 'Lease terms',
    'howItWorks.legal.doc3': 'Payment schedules',
    'howItWorks.legal.doc4': 'Ongoing obligations',
    'howItWorks.legal.closing': 'Our role is to ensure you understand exactly what you are buying and how it functions in practice.',
    'howItWorks.faq.title': 'Frequently Asked Questions',
    'howItWorks.faq.q1': 'Can foreigners legally own property in Indonesia?',
    'howItWorks.faq.a1': 'Yes. While foreigners cannot hold freehold land, leasehold (Hak Sewa) and other legal structures allow safe, long-term ownership and control of property.',
    'howItWorks.faq.q2': 'Can I resell my property?',
    'howItWorks.faq.a2': 'Yes. Leasehold properties can be sold to another buyer, transferred, or assigned according to Indonesian law and project terms.',
    'howItWorks.faq.q3': 'Can I use the unit myself?',
    'howItWorks.faq.a3': 'Yes. Owners may stay in their property subject to project rules and any agreed rental calendar.',
    'howItWorks.faq.q4': 'How is rental income paid?',
    'howItWorks.faq.a4': 'Income is typically distributed monthly or quarterly with transparent operational reports provided by the management company.',
    'howItWorks.faq.q5': 'What happens if regulations change?',
    'howItWorks.faq.a5': 'Indonesia has a long and stable history of supporting foreign investment in tourism property. Wahi structures all projects conservatively to minimize regulatory risk.',
    'howItWorks.risks.title': 'Risks to Understand',
    'howItWorks.risks.description': 'Like any international investment, buying property in Indonesia involves considerations such as:',
    'howItWorks.risks.item1': 'Currency fluctuations',
    'howItWorks.risks.item2': 'Tourism market cycles',
    'howItWorks.risks.item3': 'Operational performance',
    'howItWorks.risks.item4': 'Changes in local regulations',
    'howItWorks.risks.closing': 'Wahi does not promise or guarantee returns. We focus on conservative planning, realistic assumptions, and professional execution to create resilient long-term assets.',
    'howItWorks.cta.title': 'Have Questions?',
    'howItWorks.cta.description': 'Speak with a Wahi representative to discuss your situation and objectives.',
    'howItWorks.cta.button': 'Book a Consultation',
    
    // Contact Page
    'contact.hero.title': 'Speak With the Local Wahi Representative',
    'contact.hero.description': 'If you are considering an investment in Indonesia and would like a structured, transparent discussion, book a consultation with the local Wahi representative.',
    'contact.form.title': 'Request a Consultation',
    'contact.form.firstName': 'First Name',
    'contact.form.lastName': 'Last Name',
    'contact.form.email': 'Email Address',
    'contact.form.phone': 'Phone Number',
    'contact.form.country': 'Country of Residence',
    'contact.form.budget': 'Investment Budget Range',
    'contact.form.budgetPlaceholder': 'e.g., $200,000 - $500,000',
    'contact.form.message': 'Message',
    'contact.form.messagePlaceholder': 'Tell us about your investment interests and any questions you have.',
    'contact.form.submit': 'Submit Enquiry',
    'contact.form.sending': 'Sending...',
    'contact.form.disclaimer': 'By submitting this form, you agree to be contacted by a Wahi representative.',
    'contact.form.success.title': 'Message sent',
    'contact.form.success.description': 'We\'ll be in touch within 24 hours.',
    'contact.expect.title': 'What to Expect',
    'contact.expect.call.title': 'Initial Call',
    'contact.expect.call.description': 'A 30-minute introductory call to understand your investment objectives and answer initial questions.',
    'contact.expect.presentation.title': 'Project Presentation',
    'contact.expect.presentation.description': 'Detailed presentation of relevant projects, including specifications, pricing, and investment projections.',
    'contact.expect.structure.title': 'Structure Discussion',
    'contact.expect.structure.description': 'Review of ownership structures, legal considerations, and tax implications for your jurisdiction.',
    'contact.expect.noObligation.title': 'No Obligation',
    'contact.expect.noObligation.description': 'Our consultations are informative with no pressure. Take your time to make an informed decision.',
    'contact.rep.title': 'Your Local Representative',
    'contact.rep.name': '[Representative Name]',
    'contact.rep.role': 'Wahi Regional Representative',
    'contact.rep.photo': 'Photo',
  },
  id: {
    // Header
    'nav.home': 'Beranda',
    'nav.about': 'Tentang Kami',
    'nav.projects': 'Proyek',
    'nav.whyIndonesia': 'Mengapa Indonesia',
    'nav.howItWorks': 'Cara Kerja',
    'nav.contact': 'Kontak',
    
    // Footer
    'footer.description': 'Pendekatan transparan untuk investasi properti lintas batas di destinasi gaya hidup paling tangguh di Indonesia.',
    'footer.navigation': 'Navigasi',
    'footer.information': 'Informasi',
    'footer.legalStructures': 'Struktur Hukum',
    'footer.risksDisclaimers': 'Risiko & Penafian',
    'footer.faqs': 'FAQ',
    'footer.allRightsReserved': 'Hak cipta dilindungi.',
    'footer.baliIndonesia': 'Bali, Indonesia',
    'footer.language': 'Bahasa',
    
    // Index Page
    'index.hero.title': 'Investasi di Pasar Properti Bali dengan Performa Terbaik',
    'index.hero.subtitle': 'Wahi menawarkan kepada investor internasional akses ke properti dengan imbal hasil tinggi dan dikelola secara profesional di destinasi pariwisata paling dinamis di Asia Tenggara.',
    'index.hero.bookConsultation': 'Jadwalkan Konsultasi',
    'index.hero.exploreProjects': 'Jelajahi Proyek',
    'index.invest.title': 'Investasi di Luar Pasar dengan Imbal Hasil Rendah',
    'index.invest.description1': 'Banyak investor internasional menemukan bahwa properti di negara asal tidak lagi memberikan pendapatan yang berarti. Dengan harga tinggi dan imbal hasil bersih sering di bawah 3%, properti residensial telah menjadi penyimpan modal daripada sumber pertumbuhan.',
    'index.invest.description2': 'Indonesia — dan khususnya Bali — menawarkan alternatif. Kombinasi permintaan pariwisata yang kuat, pasokan berkualitas terbatas, dan harga masuk yang jauh lebih rendah menciptakan peluang untuk imbal hasil 8–12% atau lebih.',
    'index.invest.description3': 'Wahi mengidentifikasi dan mengembangkan properti gaya hidup di lokasi dengan okupansi sepanjang tahun dan potensi apresiasi jangka panjang. Proyek kami dirancang untuk investor yang menginginkan pendapatan, bukan hanya kepemilikan.',
    'index.pillars.title': 'Tiga Pilar Investasi Cerdas',
    'index.pillars.quote': '"Kami membantu investor mengakses imbal hasil yang tidak lagi disediakan oleh pasar mereka sendiri."',
    'index.pillars.location': 'Lokasi',
    'index.pillars.locationDesc': 'Bali memimpin Asia Tenggara dalam pemulihan pariwisata dan permintaan gaya hidup.',
    'index.pillars.design': 'Desain',
    'index.pillars.designDesc': 'Arsitektur yang dipikirkan dengan matang yang menghasilkan tarif sewa premium.',
    'index.pillars.structure': 'Struktur',
    'index.pillars.structureDesc': 'Investasi yang jelas, legal, dan dikelola secara profesional.',
    'index.featured.title': 'Proyek Unggulan',
    'index.featured.viewAll': 'Lihat Semua Proyek',
    'index.whyBali.title': 'Mengapa Bali?',
    'index.whyBali.demand': 'Permintaan',
    'index.whyBali.demandDesc': 'Lebih dari 6,3 juta pengunjung internasional pada tahun 2024, dengan pertumbuhan yang kuat diproyeksikan.',
    'index.whyBali.supply': 'Pasokan',
    'index.whyBali.supplyDesc': 'Lahan terbatas dan kode bangunan yang ketat melindungi nilai properti.',
    'index.whyBali.returns': 'Imbal Hasil',
    'index.whyBali.returnsDesc': 'Imbal hasil sewa bersih 8–12% dapat dicapai di lokasi utama.',
    'index.whyBali.learnMore': 'Pelajari Lebih Lanjut Tentang Indonesia',
    'index.cta.title': 'Siap Memulai?',
    'index.cta.description': 'Jadwalkan konsultasi tanpa kewajiban dengan perwakilan lokal Wahi.',
    'index.cta.button': 'Jadwalkan Konsultasi',
    
    // Projects Page
    'projects.hero.title': 'Proyek Nyata. Permintaan Nyata. Imbal Hasil Nyata.',
    'projects.hero.description': 'Wahi mengembangkan properti berkualitas tinggi di lokasi dengan fundamental pariwisata yang kuat dan potensi okupansi sepanjang tahun. Setiap proyek dirancang, dibangun, dan distrukturkan untuk berkinerja sebagai investasi jangka panjang.',
    'projects.available': 'Tersedia',
    'projects.enquireNow': 'Tanyakan Sekarang',
    'projects.cta.title': 'Tidak Yakin Proyek Mana yang Cocok untuk Anda?',
    'projects.cta.description': 'Bicaralah dengan penasihat Wahi untuk membandingkan opsi dan peluang.',
    'projects.cta.button': 'Jadwalkan Konsultasi',
    
    // About Page
    'about.hero.title': 'Pengembangan Properti dengan Kejelasan, Bukan Kompleksitas',
    'about.hero.description': 'Wahi adalah perusahaan pengembangan properti dan investasi butik yang berbasis di Bali, Indonesia. Kami bekerja dengan investor internasional yang menginginkan akses yang jelas dan transparan ke properti Asia Tenggara — tanpa struktur tersembunyi, kontrak yang tidak jelas, atau hambatan bahasa.',
    'about.whoWeAre.title': 'Siapa Kami',
    'about.whoWeAre.description1': 'Wahi didirikan dengan satu tujuan: membuat investasi properti Indonesia dapat diakses, dipahami, dan menguntungkan bagi investor internasional.',
    'about.whoWeAre.description2': 'Tim kami menggabungkan keahlian lokal yang mendalam dengan perspektif global. Kami mengelola setiap langkah proses — dari pemilihan lokasi dan pengembangan hingga penjualan, strukturisasi hukum, dan manajemen properti — sehingga investor dapat berpartisipasi dengan percaya diri.',
    'about.whatWeDo.title': 'Apa yang Kami Lakukan',
    'about.whatWeDo.description': 'Wahi mengembangkan dan mengkurasi proyek properti di Bali dan lokasi Indonesia terpilih. Kami fokus pada:',
    'about.whatWeDo.item1': 'Properti gaya hidup di area permintaan tinggi',
    'about.whatWeDo.item2': 'Desain dan finishing kelas perhotelan',
    'about.whatWeDo.item3': 'Struktur kepemilikan yang jelas untuk pembeli asing',
    'about.whatWeDo.item4': 'Manajemen sewa dan properti profesional',
    'about.whatWeDo.closing': 'Setiap proyek dirancang untuk menghasilkan pendapatan sewa sambil menawarkan apresiasi modal jangka panjang.',
    'about.whyReliable.title': 'Mengapa Wahi adalah Mitra yang Dapat Diandalkan',
    'about.whyReliable.item1': 'Kehadiran lokal di Bali dengan kantor regional di pasar utama',
    'about.whyReliable.item2': 'Keterlibatan end-to-end — kami mengembangkan, menjual, dan mengelola',
    'about.whyReliable.item3': 'Hubungan langsung dengan notaris, penasihat hukum, dan bank',
    'about.whyReliable.item4': 'Harga transparan dan dokumentasi yang jelas',
    'about.whyReliable.item5': 'Rekam jejak dalam perhotelan dan investasi properti',
    'about.localOffice.title': 'Peran Kantor Lokal di [COUNTRY]',
    'about.localOffice.intro': 'Wahi [COUNTRY] adalah titik kontak lokal Anda untuk investasi properti Indonesia.',
    'about.localOffice.purpose': 'Tujuan kantor regional adalah membuat investasi lintas batas menjadi sederhana, jelas, dan nyaman bagi investor yang berbasis di [COUNTRY].',
    'about.localOffice.provides': 'Perwakilan lokal menyediakan:',
    'about.localOffice.item1': 'Konsultasi personal dalam bahasa dan zona waktu Anda',
    'about.localOffice.item2': 'Penjelasan yang jelas tentang struktur properti Indonesia',
    'about.localOffice.item3': 'Panduan tentang pertimbangan hukum dan keuangan',
    'about.localOffice.item4': 'Koordinasi dengan agen properti lokal',
    'about.localOffice.item5': 'Bantuan selama proses pembelian',
    'about.localOffice.item6': 'Dukungan berkelanjutan setelah pembelian',
    'about.localOffice.closing': 'Daripada berurusan langsung dengan pengembang luar negeri, Anda memiliki penasihat lokal yang berpengetahuan yang memahami pasar Indonesia dan harapan investor dari [COUNTRY].',
    'about.investorProcess.title': 'Cara Kami Bekerja dengan Investor',
    'about.investorProcess.item1': 'Konsultasi awal untuk memahami tujuan dan anggaran',
    'about.investorProcess.item2': 'Presentasi proyek dan unit yang sesuai',
    'about.investorProcess.item3': 'Penjelasan yang jelas tentang struktur hukum dan biaya',
    'about.investorProcess.item4': 'Dukungan melalui dokumentasi dan pembayaran',
    'about.investorProcess.item5': 'Koordinasi dengan profesional hukum dan keuangan',
    'about.investorProcess.item6': 'Komunikasi berkelanjutan selama konstruksi dan serah terima',
    'about.investorProcess.item7': 'Onboarding sewa dan manajemen properti',
    'about.investorProcess.closing': 'Di setiap tahap, perwakilan lokal Wahi tetap menjadi kontak utama Anda, sementara tim Indonesia menangani pengiriman proyek dan operasi.',
    'about.longTerm.title': 'Pendekatan Jangka Panjang',
    'about.longTerm.item1': 'Harga yang adil dan sesuai pasar',
    'about.longTerm.item2': 'Desain berkelanjutan yang berfokus pada kualitas',
    'about.longTerm.item3': 'Hubungan investor berulang',
    'about.longTerm.item4': 'Panduan jujur, bahkan ketika jawabannya adalah "tidak"',
    'about.longTerm.closing': 'Bisnis kami bergantung pada kepercayaan — dan kami mendapatkannya melalui transparansi, konsistensi, dan hasil.',
    'about.cta.title': 'Siap Berbicara?',
    'about.cta.description': 'Jadwalkan konsultasi untuk mempelajari bagaimana Wahi dapat membantu Anda berinvestasi di properti Indonesia.',
    'about.cta.button': 'Jadwalkan Konsultasi',
    
    // Why Invest Page
    'whyInvest.hero.title': 'Mengapa Berinvestasi di Indonesia?',
    'whyInvest.hero.description': 'Bagi investor dari [COUNTRY], pasar properti di dalam negeri sering memberikan imbal hasil yang sederhana. Indonesia menawarkan profil yang berbeda: ekonomi yang berkembang pesat, destinasi yang diakui secara global, dan permintaan pariwisata sepanjang tahun yang mendukung imbal hasil sewa yang jauh lebih tinggi.\n\nHalaman ini menjelaskan, dalam istilah praktis, mengapa Indonesia — dan khususnya Bali — telah menjadi salah satu pasar investasi properti paling menarik di Asia.',
    'whyInvest.demand.title': 'Lebih Banyak Permintaan Daripada Pasokan Berkualitas',
    'whyInvest.demand.description': 'Bali tetap menjadi salah satu destinasi paling diinginkan di Asia Tenggara. Setelah pandemi, kedatangan internasional telah pulih dengan tajam — dan permintaan akan akomodasi berkualitas tinggi terus melampaui pasokan.',
    'whyInvest.demand.item1': '6,3 juta+ pengunjung internasional ke Bali pada tahun 2024',
    'whyInvest.demand.item2': 'Kehadiran digital nomad dan wisatawan gaya hidup yang kuat',
    'whyInvest.demand.item3': 'Inventaris berkualitas terbatas di lokasi premium',
    'whyInvest.demand.item4': 'Pariwisata sepanjang tahun dengan penurunan musiman minimal',
    'whyInvest.demand.closing': 'Bagi investor, ketidakseimbangan antara permintaan dan pasokan ini mendukung:',
    'whyInvest.demand.benefit1': 'okupansi yang kuat',
    'whyInvest.demand.benefit2': 'tarif malam yang kompetitif',
    'whyInvest.demand.benefit3': 'apresiasi nilai jangka panjang',
    'whyInvest.prices.title': 'Harga Lebih Rendah, Pendapatan Lebih Tinggi',
    'whyInvest.prices.description': 'Dibandingkan dengan kota-kota besar di [COUNTRY], Bali menawarkan harga masuk yang jauh lebih rendah untuk kualitas yang sebanding.',
    'whyInvest.prices.item1': 'Vila premium mulai dari USD 250.000–500.000',
    'whyInvest.prices.item2': 'Imbal hasil sewa bersih 8–12% dapat dicapai',
    'whyInvest.prices.item3': 'Apresiasi modal 5–10% per tahun di area tertentu',
    'whyInvest.prices.closing': 'Kombinasi biaya yang lebih rendah dan imbal hasil yang lebih tinggi ini menciptakan peluang yang jarang tersedia di pasar yang lebih maju.',
    'whyInvest.growth.title': 'Didukung oleh Pertumbuhan Ekonomi Jangka Panjang',
    'whyInvest.growth.description': 'Indonesia adalah ekonomi terbesar di Asia Tenggara, dengan:',
    'whyInvest.growth.item1': 'Populasi 275 juta+',
    'whyInvest.growth.item2': 'Pertumbuhan PDB konsisten di atas 5% per tahun',
    'whyInvest.growth.item3': 'Investasi pemerintah dalam infrastruktur dan pariwisata',
    'whyInvest.growth.item4': 'Lingkungan hukum yang stabil untuk kepemilikan properti',
    'whyInvest.growth.closing': 'Pariwisata tetap menjadi industri nasional strategis, dengan investasi berkelanjutan ke bandara, jalan, dan layanan—memperkuat prospek jangka panjang bagi pemilik properti.',
    'whyInvest.diversification.title': 'Manfaat Diversifikasi Portofolio',
    'whyInvest.diversification.description': 'Bagi investor internasional, properti Indonesia menawarkan:',
    'whyInvest.diversification.item1': 'Paparan terhadap pertumbuhan pasar berkembang',
    'whyInvest.diversification.item2': 'Aset di luar tren properti [COUNTRY]',
    'whyInvest.diversification.item3': 'Pendapatan dalam denominasi USD dalam banyak kasus',
    'whyInvest.diversification.item4': 'Nilai gaya hidup sebagai manfaat sekunder',
    'whyInvest.alternative.title': 'Alternatif yang Menarik untuk Pasar dengan Imbal Hasil Rendah',
    'whyInvest.alternative.description': 'Bagi investor di [COUNTRY] yang menghadapi harga tinggi dan imbal hasil rendah di dalam negeri, Indonesia menawarkan kombinasi langka:',
    'whyInvest.alternative.item1': 'Titik masuk yang terjangkau',
    'whyInvest.alternative.item2': 'Permintaan sewa yang kuat',
    'whyInvest.alternative.item3': 'Infrastruktur manajemen profesional',
    'whyInvest.alternative.item4': 'Struktur hukum yang dirancang untuk kepemilikan asing',
    'whyInvest.alternative.closing': 'Dengan proyek yang tepat dan mitra yang tepat, properti Indonesia dapat menjadi tambahan yang kuat untuk portofolio investasi yang terdiversifikasi.',
    'whyInvest.cta.title': 'Mulai Menjelajah',
    'whyInvest.cta.description': 'Jika Anda mempertimbangkan Indonesia sebagai bagian dari strategi investasi Anda, kami siap membantu.',
    'whyInvest.cta.button': 'Lihat Pengembangan Saat Ini',
    
    // How It Works Page
    'howItWorks.hero.title': 'Membeli Properti di Bali – Jelas, Legal, dan Terstruktur',
    'howItWorks.hero.description': 'Berinvestasi di properti Indonesia adalah hal yang mudah ketika didekati dengan struktur yang tepat dan panduan profesional. Halaman ini menjelaskan – dalam istilah praktis – bagaimana investor asing membeli, memiliki, dan mendapatkan penghasilan dari properti yang dikembangkan oleh Wahi. Tujuan kami adalah menghilangkan ketidakpastian dan menyediakan kerangka kerja yang transparan, langkah demi langkah dari pertanyaan pertama hingga kepemilikan yang selesai.',
    'howItWorks.hakSewa.title': 'Model Paling Umum: Hak Sewa (Leasehold)',
    'howItWorks.hakSewa.description': 'Proyek Wahi untuk pembeli internasional terutama distrukturkan menggunakan Hak Sewa – kepemilikan sewa jangka panjang. Ini adalah cara standar dan paling praktis bagi orang asing untuk memiliki properti di Indonesia.',
    'howItWorks.hakSewa.terms': 'Ketentuan umum:',
    'howItWorks.hakSewa.item1': 'Periode sewa awal: sekitar 25–30 tahun',
    'howItWorks.hakSewa.item2': 'Hak perpanjangan yang dijamin secara kontraktual',
    'howItWorks.hakSewa.item3': 'Kontrol hukum penuh atas unit selama masa sewa',
    'howItWorks.hakSewa.item4': 'Hak untuk menyewa, menjual kembali, atau mengalihkan properti',
    'howItWorks.hakSewa.item5': 'Hak Sewa banyak digunakan di seluruh Bali dan Indonesia untuk vila, apartemen, dan residensi resor dan diakui sebagai struktur yang aman dan dapat dibiayai',
    'howItWorks.misconception.title': 'Kesalahpahaman Umum Tentang Perpanjangan',
    'howItWorks.misconception.description': 'Banyak pembeli pertama kali khawatir bahwa memperpanjang sewa berarti "membeli seluruh properti lagi." Ini tidak benar. Ketika sewa diperpanjang, pemilik biasanya hanya membayar untuk:',
    'howItWorks.misconception.item1': 'Nilai porsi tanah',
    'howItWorks.misconception.item2': 'Bukan untuk bangunan itu sendiri',
    'howItWorks.misconception.example': 'Contoh',
    'howItWorks.misconception.exampleLine1': 'Harga pembelian unit: USD 300.000',
    'howItWorks.misconception.exampleLine2': 'Nilai bangunan: mayoritas dari harga',
    'howItWorks.misconception.exampleLine3': 'Nilai tanah: komponen yang lebih kecil',
    'howItWorks.misconception.exampleNote': 'Pada saat perpanjangan, biayanya biasanya hanya 10–20% dari harga pembelian asli, tergantung pada proyek dan nilai tanah pada saat itu.',
    'howItWorks.misconception.closing': 'Ini membuat kepemilikan jangka panjang dapat diprediksi dan ekonomis.',
    'howItWorks.process.title': 'Dari Kontak Pertama hingga Kepemilikan',
    'howItWorks.process.subtitle': 'Proses Langkah demi Langkah',
    'howItWorks.process.step1.title': 'Konsultasi Awal',
    'howItWorks.process.step1.description': 'Diskusi tentang tujuan, anggaran, dan proyek pilihan Anda.',
    'howItWorks.process.step2.title': 'Pemilihan Proyek',
    'howItWorks.process.step2.description': 'Tinjau unit yang tersedia, harga, dan jadwal yang diharapkan.',
    'howItWorks.process.step3.title': 'Reservasi',
    'howItWorks.process.step3.description': 'Deposit pemesanan kecil mengamankan unit yang dipilih.',
    'howItWorks.process.step4.title': 'Dokumentasi Hukum',
    'howItWorks.process.step4.description': 'Perjanjian penjualan formal dan kontrak sewa yang disiapkan oleh notaris dan profesional hukum.',
    'howItWorks.process.step5.title': 'Tahapan Pembayaran',
    'howItWorks.process.step5.description': 'Pembayaran dikaitkan dengan tahap konstruksi atau jadwal yang disepakati.',
    'howItWorks.process.step6.title': 'Konstruksi & Pembaruan',
    'howItWorks.process.step6.description': 'Laporan kemajuan dan pembaruan lokasi secara berkala.',
    'howItWorks.process.step7.title': 'Serah Terima',
    'howItWorks.process.step7.description': 'Penyelesaian unit, perabotan (jika berlaku), dan dokumentasi akhir.',
    'howItWorks.process.step8.title': 'Onboarding Sewa',
    'howItWorks.process.step8.description': 'Pengaturan manajemen properti dan generasi pendapatan dimulai.',
    'howItWorks.rental.title': 'Pendapatan Sewa & Manajemen',
    'howItWorks.rental.description': 'Sebagian besar pembeli Wahi adalah investor luar negeri yang menginginkan pengalaman yang sepenuhnya hands-off. Setiap proyek dirancang dengan operasi profesional dalam pikiran:',
    'howItWorks.rental.item1': 'Tim manajemen di lokasi',
    'howItWorks.rental.item2': 'Pemasaran dan pemesanan',
    'howItWorks.rental.item3': 'Pemeliharaan dan pelaporan',
    'howItWorks.rental.item4': 'Laporan keuangan transparan',
    'howItWorks.rental.optionsIntro': 'Pemilik biasanya dapat memilih antara:',
    'howItWorks.rental.option1': 'Penggunaan investasi murni',
    'howItWorks.rental.option2': 'Penggunaan pribadi sebagian dengan pendapatan sewa',
    'howItWorks.rental.option3': 'Strategi penyewaan jangka panjang',
    'howItWorks.rental.closing': 'Semua detail dijelaskan dengan jelas sebelum pembelian sehingga harapan tetap realistis dan selaras.',
    'howItWorks.legal.title': 'Transparansi Hukum dan Keuangan',
    'howItWorks.legal.intro': 'Wahi hanya bekerja dengan:',
    'howItWorks.legal.item1': 'Notaris Indonesia berlisensi',
    'howItWorks.legal.item2': 'Penasihat hukum terkemuka',
    'howItWorks.legal.item3': 'Mitra manajemen properti yang mapan',
    'howItWorks.legal.docsIntro': 'Setiap langkah didokumentasikan, dan investor menerima penjelasan yang jelas tentang:',
    'howItWorks.legal.doc1': 'Hak kepemilikan',
    'howItWorks.legal.doc2': 'Ketentuan sewa',
    'howItWorks.legal.doc3': 'Jadwal pembayaran',
    'howItWorks.legal.doc4': 'Kewajiban berkelanjutan',
    'howItWorks.legal.closing': 'Peran kami adalah memastikan Anda memahami dengan tepat apa yang Anda beli dan bagaimana fungsinya dalam praktik.',
    'howItWorks.faq.title': 'Pertanyaan yang Sering Diajukan',
    'howItWorks.faq.q1': 'Bisakah orang asing secara legal memiliki properti di Indonesia?',
    'howItWorks.faq.a1': 'Ya. Meskipun orang asing tidak dapat memegang tanah hak milik, hak sewa dan struktur hukum lainnya memungkinkan kepemilikan dan kontrol properti yang aman dan jangka panjang.',
    'howItWorks.faq.q2': 'Bisakah saya menjual kembali properti saya?',
    'howItWorks.faq.a2': 'Ya. Properti hak sewa dapat dijual ke pembeli lain, dialihkan, atau ditugaskan sesuai dengan hukum Indonesia dan ketentuan proyek.',
    'howItWorks.faq.q3': 'Bisakah saya menggunakan unit sendiri?',
    'howItWorks.faq.a3': 'Ya. Pemilik dapat tinggal di properti mereka sesuai dengan aturan proyek dan kalender sewa yang disepakati.',
    'howItWorks.faq.q4': 'Bagaimana pendapatan sewa dibayarkan?',
    'howItWorks.faq.a4': 'Pendapatan biasanya didistribusikan bulanan atau triwulanan dengan laporan operasional transparan yang disediakan oleh perusahaan manajemen.',
    'howItWorks.faq.q5': 'Apa yang terjadi jika peraturan berubah?',
    'howItWorks.faq.a5': 'Indonesia memiliki sejarah panjang dan stabil dalam mendukung investasi asing di properti pariwisata. Wahi menyusun semua proyek secara konservatif untuk meminimalkan risiko regulasi.',
    'howItWorks.risks.title': 'Risiko yang Perlu Dipahami',
    'howItWorks.risks.description': 'Seperti investasi internasional lainnya, membeli properti di Indonesia melibatkan pertimbangan seperti:',
    'howItWorks.risks.item1': 'Fluktuasi mata uang',
    'howItWorks.risks.item2': 'Siklus pasar pariwisata',
    'howItWorks.risks.item3': 'Kinerja operasional',
    'howItWorks.risks.item4': 'Perubahan peraturan lokal',
    'howItWorks.risks.closing': 'Wahi tidak menjanjikan atau menjamin imbal hasil. Kami fokus pada perencanaan konservatif, asumsi realistis, dan eksekusi profesional untuk menciptakan aset jangka panjang yang tangguh.',
    'howItWorks.cta.title': 'Ada Pertanyaan?',
    'howItWorks.cta.description': 'Bicaralah dengan perwakilan Wahi untuk mendiskusikan situasi dan tujuan Anda.',
    'howItWorks.cta.button': 'Jadwalkan Konsultasi',
    
    // Contact Page
    'contact.hero.title': 'Berbicara dengan Perwakilan Lokal Wahi',
    'contact.hero.description': 'Jika Anda mempertimbangkan investasi di Indonesia dan menginginkan diskusi yang terstruktur dan transparan, jadwalkan konsultasi dengan perwakilan lokal Wahi.',
    'contact.form.title': 'Minta Konsultasi',
    'contact.form.firstName': 'Nama Depan',
    'contact.form.lastName': 'Nama Belakang',
    'contact.form.email': 'Alamat Email',
    'contact.form.phone': 'Nomor Telepon',
    'contact.form.country': 'Negara Tempat Tinggal',
    'contact.form.budget': 'Kisaran Anggaran Investasi',
    'contact.form.budgetPlaceholder': 'mis., $200.000 - $500.000',
    'contact.form.message': 'Pesan',
    'contact.form.messagePlaceholder': 'Ceritakan tentang minat investasi Anda dan pertanyaan yang Anda miliki.',
    'contact.form.submit': 'Kirim Pertanyaan',
    'contact.form.sending': 'Mengirim...',
    'contact.form.disclaimer': 'Dengan mengirimkan formulir ini, Anda setuju untuk dihubungi oleh perwakilan Wahi.',
    'contact.form.success.title': 'Pesan terkirim',
    'contact.form.success.description': 'Kami akan menghubungi Anda dalam 24 jam.',
    'contact.expect.title': 'Apa yang Diharapkan',
    'contact.expect.call.title': 'Panggilan Awal',
    'contact.expect.call.description': 'Panggilan pengantar 30 menit untuk memahami tujuan investasi Anda dan menjawab pertanyaan awal.',
    'contact.expect.presentation.title': 'Presentasi Proyek',
    'contact.expect.presentation.description': 'Presentasi detail proyek yang relevan, termasuk spesifikasi, harga, dan proyeksi investasi.',
    'contact.expect.structure.title': 'Diskusi Struktur',
    'contact.expect.structure.description': 'Tinjauan struktur kepemilikan, pertimbangan hukum, dan implikasi pajak untuk yurisdiksi Anda.',
    'contact.expect.noObligation.title': 'Tanpa Kewajiban',
    'contact.expect.noObligation.description': 'Konsultasi kami bersifat informatif tanpa tekanan. Luangkan waktu Anda untuk membuat keputusan yang tepat.',
    'contact.rep.title': 'Perwakilan Lokal Anda',
    'contact.rep.name': '[Nama Perwakilan]',
    'contact.rep.role': 'Perwakilan Regional Wahi',
    'contact.rep.photo': 'Foto',
  },
  zh: {
    // Header
    'nav.home': '首页',
    'nav.about': '关于我们',
    'nav.projects': '项目',
    'nav.whyIndonesia': '为什么选择印尼',
    'nav.howItWorks': '运作方式',
    'nav.contact': '联系我们',
    
    // Footer
    'footer.description': '透明的跨境房地产投资方式，投资印尼最具韧性的生活方式目的地。',
    'footer.navigation': '导航',
    'footer.information': '信息',
    'footer.legalStructures': '法律结构',
    'footer.risksDisclaimers': '风险与免责声明',
    'footer.faqs': '常见问题',
    'footer.allRightsReserved': '版权所有。',
    'footer.baliIndonesia': '印尼巴厘岛',
    'footer.language': '语言',
    
    // Index Page
    'index.hero.title': '投资巴厘岛表现最佳的房地产市场',
    'index.hero.subtitle': 'Wahi为国际投资者提供东南亚最具活力的旅游目的地的高收益、专业管理房地产投资机会。',
    'index.hero.bookConsultation': '预约咨询',
    'index.hero.exploreProjects': '探索项目',
    'index.invest.title': '超越低收益市场的投资',
    'index.invest.description1': '许多国际投资者发现，国内房产不再能带来有意义的收入。由于价格高昂，净收益率通常低于3%，住宅房地产已成为资本储存而非增长来源。',
    'index.invest.description2': '印尼——尤其是巴厘岛——提供了另一种选择。强劲的旅游需求、有限的优质供应和显著较低的入门价格相结合，创造了8-12%或更高收益率的机会。',
    'index.invest.description3': 'Wahi在全年高入住率和长期升值潜力的地点识别和开发生活方式物业。我们的项目专为希望获得收入而非仅仅拥有产权的投资者而设计。',
    'index.pillars.title': '智慧投资的三大支柱',
    'index.pillars.quote': '"我们帮助投资者获得其本国市场不再提供的回报。"',
    'index.pillars.location': '位置',
    'index.pillars.locationDesc': '巴厘岛在旅游复苏和生活方式需求方面领先东南亚。',
    'index.pillars.design': '设计',
    'index.pillars.designDesc': '精心设计的建筑可获得高端租金。',
    'index.pillars.structure': '结构',
    'index.pillars.structureDesc': '清晰、合法、专业管理的投资。',
    'index.featured.title': '精选项目',
    'index.featured.viewAll': '查看所有项目',
    'index.whyBali.title': '为什么选择巴厘岛？',
    'index.whyBali.demand': '需求',
    'index.whyBali.demandDesc': '2024年超过630万国际游客，预计将持续强劲增长。',
    'index.whyBali.supply': '供应',
    'index.whyBali.supplyDesc': '有限的土地和严格的建筑法规保护房产价值。',
    'index.whyBali.returns': '回报',
    'index.whyBali.returnsDesc': '在优质地段可实现8-12%的净租金收益率。',
    'index.whyBali.learnMore': '了解更多关于印尼的信息',
    'index.cta.title': '准备开始了吗？',
    'index.cta.description': '与当地Wahi代表预约无义务咨询。',
    'index.cta.button': '预约咨询',
    
    // Projects Page
    'projects.hero.title': '真实项目。真实需求。真实回报。',
    'projects.hero.description': 'Wahi在旅游基础设施完善、全年高入住率的地区开发高品质房产。每个项目都经过设计、建造和结构化，以实现长期投资价值。',
    'projects.available': '可购买',
    'projects.enquireNow': '立即咨询',
    'projects.cta.title': '不确定哪个项目最适合您？',
    'projects.cta.description': '与Wahi顾问交流，比较选项和机会。',
    'projects.cta.button': '预约咨询',
    
    // About Page
    'about.hero.title': '清晰而非复杂的房产开发',
    'about.hero.description': 'Wahi是一家总部位于印尼巴厘岛的精品房产开发和投资公司。我们与希望清晰、透明地进入东南亚房地产市场的国际投资者合作——没有隐藏结构、不明确的合同或语言障碍。',
    'about.whoWeAre.title': '我们是谁',
    'about.whoWeAre.description1': 'Wahi成立的唯一目标是：使印尼房产投资对国际投资者来说易于获取、易于理解且有回报。',
    'about.whoWeAre.description2': '我们的团队结合了深厚的本地专业知识和全球视野。我们管理流程的每一步——从选址和开发到销售、法律结构和物业管理——以便投资者可以充满信心地参与。',
    'about.whatWeDo.title': '我们做什么',
    'about.whatWeDo.description': 'Wahi在巴厘岛和印尼精选地点开发和策划房地产项目。我们专注于：',
    'about.whatWeDo.item1': '高需求地区的生活方式物业',
    'about.whatWeDo.item2': '酒店级设计和装修',
    'about.whatWeDo.item3': '为外国买家提供清晰的产权结构',
    'about.whatWeDo.item4': '专业的租赁和物业管理',
    'about.whatWeDo.closing': '每个项目都旨在产生租金收入，同时提供长期资本增值。',
    'about.whyReliable.title': '为什么Wahi是可靠的合作伙伴',
    'about.whyReliable.item1': '在巴厘岛设有本地机构，在主要市场设有区域办事处',
    'about.whyReliable.item2': '端到端参与——我们开发、销售和管理',
    'about.whyReliable.item3': '与公证人、法律顾问和银行有直接关系',
    'about.whyReliable.item4': '透明的定价和清晰的文件',
    'about.whyReliable.item5': '在酒店和房产投资方面有良好记录',
    'about.localOffice.title': '[COUNTRY]本地办公室的角色',
    'about.localOffice.intro': 'Wahi [COUNTRY]是您进行印尼房产投资的本地联系点。',
    'about.localOffice.purpose': '区域办公室的目的是使跨境投资对[COUNTRY]的投资者来说变得简单、清晰和舒适。',
    'about.localOffice.provides': '本地代表提供：',
    'about.localOffice.item1': '使用您的语言和时区进行个人咨询',
    'about.localOffice.item2': '清晰解释印尼房产结构',
    'about.localOffice.item3': '法律和财务方面的指导',
    'about.localOffice.item4': '与当地房产代理协调',
    'about.localOffice.item5': '购买过程中的全程协助',
    'about.localOffice.item6': '购买后的持续支持',
    'about.localOffice.closing': '您无需直接与海外开发商打交道，而是拥有一位了解印尼市场和[COUNTRY]投资者期望的知识渊博的本地顾问。',
    'about.investorProcess.title': '我们如何与投资者合作',
    'about.investorProcess.item1': '初步咨询以了解目标和预算',
    'about.investorProcess.item2': '展示合适的项目和单位',
    'about.investorProcess.item3': '清晰解释法律结构和费用',
    'about.investorProcess.item4': '文件和付款方面的支持',
    'about.investorProcess.item5': '与法律和财务专业人士协调',
    'about.investorProcess.item6': '在建设和交付过程中持续沟通',
    'about.investorProcess.item7': '租赁入驻和物业管理',
    'about.investorProcess.closing': '在每个阶段，Wahi本地代表始终是您的主要联系人，而印尼团队负责项目交付和运营。',
    'about.longTerm.title': '长期方法',
    'about.longTerm.item1': '公平、符合市场的定价',
    'about.longTerm.item2': '可持续、注重质量的设计',
    'about.longTerm.item3': '重复投资者关系',
    'about.longTerm.item4': '诚实的指导，即使答案是"不"',
    'about.longTerm.closing': '我们的业务依赖于信任——我们通过透明、一致和成果来赢得信任。',
    'about.cta.title': '准备好交谈了吗？',
    'about.cta.description': '预约咨询，了解Wahi如何帮助您投资印尼房产。',
    'about.cta.button': '预约咨询',
    
    // Why Invest Page
    'whyInvest.hero.title': '为什么投资印尼？',
    'whyInvest.hero.description': '对于来自[COUNTRY]的投资者，国内房产市场通常只能带来适度的回报。印尼提供了不同的格局：快速增长的经济、全球知名的目的地以及全年旅游需求，支持显著更高的租金收益率。\n\n本页从实际角度解释了为什么印尼——尤其是巴厘岛——已成为亚洲最具吸引力的房产投资市场之一。',
    'whyInvest.demand.title': '需求大于优质供应',
    'whyInvest.demand.description': '巴厘岛仍然是东南亚最受欢迎的目的地之一。疫情后，国际游客人数大幅反弹——对高品质住宿的需求持续超过供应。',
    'whyInvest.demand.item1': '2024年巴厘岛国际游客超过630万',
    'whyInvest.demand.item2': '数字游民和生活方式旅行者数量强劲',
    'whyInvest.demand.item3': '优质地段的优质库存有限',
    'whyInvest.demand.item4': '全年旅游，季节性下降最小',
    'whyInvest.demand.closing': '对于投资者来说，需求和供应之间的这种不平衡支持：',
    'whyInvest.demand.benefit1': '强劲的入住率',
    'whyInvest.demand.benefit2': '有竞争力的每晚房价',
    'whyInvest.demand.benefit3': '长期价值增值',
    'whyInvest.prices.title': '价格更低，收入更高',
    'whyInvest.prices.description': '与[COUNTRY]的主要城市相比，巴厘岛以显著较低的价格提供相当质量的房产。',
    'whyInvest.prices.item1': '优质别墅起价25万-50万美元',
    'whyInvest.prices.item2': '可实现8-12%的净租金收益率',
    'whyInvest.prices.item3': '精选地区每年资本增值5-10%',
    'whyInvest.prices.closing': '较低成本和较高收益率的组合创造了在更发达市场很少见的机会。',
    'whyInvest.growth.title': '长期经济增长支撑',
    'whyInvest.growth.description': '印尼是东南亚最大的经济体：',
    'whyInvest.growth.item1': '人口超过2.75亿',
    'whyInvest.growth.item2': 'GDP年增长率持续保持在5%以上',
    'whyInvest.growth.item3': '政府对基础设施和旅游业的投资',
    'whyInvest.growth.item4': '稳定的房产所有权法律环境',
    'whyInvest.growth.closing': '旅游业仍然是战略性国家产业，持续投资于机场、道路和服务——加强了房产所有者的长期前景。',
    'whyInvest.diversification.title': '投资组合多元化优势',
    'whyInvest.diversification.description': '对于国际投资者，印尼房产提供：',
    'whyInvest.diversification.item1': '新兴市场增长的敞口',
    'whyInvest.diversification.item2': '[COUNTRY]房产趋势之外的资产',
    'whyInvest.diversification.item3': '在许多情况下以美元计价的收入',
    'whyInvest.diversification.item4': '作为次要利益的生活方式价值',
    'whyInvest.alternative.title': '低收益市场的有力替代选择',
    'whyInvest.alternative.description': '对于[COUNTRY]面临高价格和低回报的投资者，印尼提供了罕见的组合：',
    'whyInvest.alternative.item1': '可负担的入门价格',
    'whyInvest.alternative.item2': '强劲的租赁需求',
    'whyInvest.alternative.item3': '专业的管理基础设施',
    'whyInvest.alternative.item4': '专为外国所有权设计的法律结构',
    'whyInvest.alternative.closing': '有了合适的项目和合适的合作伙伴，印尼房产可以成为多元化投资组合的有力补充。',
    'whyInvest.cta.title': '开始探索',
    'whyInvest.cta.description': '如果您正在考虑将印尼作为投资策略的一部分，我们随时为您提供帮助。',
    'whyInvest.cta.button': '查看当前开发项目',
    
    // How It Works Page
    'howItWorks.hero.title': '在巴厘岛购买房产——清晰、合法、有结构',
    'howItWorks.hero.description': '在采用正确的结构和专业指导时，投资印尼房地产是简单明了的。本页从实际角度解释了外国投资者如何购买、拥有和从Wahi开发的房产中获得收入。我们的目标是消除不确定性，提供从首次咨询到完成所有权的透明、逐步框架。',
    'howItWorks.hakSewa.title': '最常见的模式：Hak Sewa（租赁权）',
    'howItWorks.hakSewa.description': 'Wahi为国际买家设计的项目主要采用Hak Sewa——长期租赁所有权。这是外国人在印尼拥有房产的标准和最实用的方式。',
    'howItWorks.hakSewa.terms': '典型条款：',
    'howItWorks.hakSewa.item1': '初始租期：约25-30年',
    'howItWorks.hakSewa.item2': '合同保证的续期权',
    'howItWorks.hakSewa.item3': '租期内对单位的完全法律控制',
    'howItWorks.hakSewa.item4': '出租、转售或转让房产的权利',
    'howItWorks.hakSewa.item5': '租赁权在巴厘岛和印尼的别墅、公寓和度假村住宅中广泛使用，被认为是安全且可融资的结构',
    'howItWorks.misconception.title': '关于续期的常见误解',
    'howItWorks.misconception.description': '许多首次购买者担心续期意味着"再次购买整个房产"。事实并非如此。续期时，业主通常只需支付：',
    'howItWorks.misconception.item1': '土地部分的价值',
    'howItWorks.misconception.item2': '不包括建筑本身',
    'howItWorks.misconception.example': '示例',
    'howItWorks.misconception.exampleLine1': '单位购买价格：30万美元',
    'howItWorks.misconception.exampleLine2': '建筑价值：占价格的大部分',
    'howItWorks.misconception.exampleLine3': '土地价值：较小的部分',
    'howItWorks.misconception.exampleNote': '续期时，费用通常仅为原始购买价格的10-20%，具体取决于项目和当时的土地价值。',
    'howItWorks.misconception.closing': '这使得长期所有权既可预测又经济合理。',
    'howItWorks.process.title': '从首次联系到所有权',
    'howItWorks.process.subtitle': '逐步流程',
    'howItWorks.process.step1.title': '初步咨询',
    'howItWorks.process.step1.description': '讨论您的目标、预算和首选项目。',
    'howItWorks.process.step2.title': '项目选择',
    'howItWorks.process.step2.description': '查看可用单位、定价和预期时间表。',
    'howItWorks.process.step3.title': '预订',
    'howItWorks.process.step3.description': '小额预订押金可锁定所选单位。',
    'howItWorks.process.step4.title': '法律文件',
    'howItWorks.process.step4.description': '由公证人和法律专业人员准备正式销售协议和租赁合同。',
    'howItWorks.process.step5.title': '付款里程碑',
    'howItWorks.process.step5.description': '付款与建设阶段或约定时间表挂钩。',
    'howItWorks.process.step6.title': '建设与更新',
    'howItWorks.process.step6.description': '定期进度报告和现场更新。',
    'howItWorks.process.step7.title': '交付',
    'howItWorks.process.step7.description': '单位完工、装修（如适用）和最终文件。',
    'howItWorks.process.step8.title': '租赁入驻',
    'howItWorks.process.step8.description': '物业管理设置和收入生成开始。',
    'howItWorks.rental.title': '租金收入与管理',
    'howItWorks.rental.description': '大多数Wahi买家是希望完全不需要亲自参与的海外投资者。每个项目都以专业运营为设计考量：',
    'howItWorks.rental.item1': '现场管理团队',
    'howItWorks.rental.item2': '营销和预订',
    'howItWorks.rental.item3': '维护和报告',
    'howItWorks.rental.item4': '透明的财务报表',
    'howItWorks.rental.optionsIntro': '业主通常可以选择：',
    'howItWorks.rental.option1': '纯投资使用',
    'howItWorks.rental.option2': '部分个人使用并获得租金收入',
    'howItWorks.rental.option3': '长期租赁策略',
    'howItWorks.rental.closing': '所有细节在购买前都会清楚解释，以确保期望保持现实和一致。',
    'howItWorks.legal.title': '法律和财务透明度',
    'howItWorks.legal.intro': 'Wahi仅与以下机构合作：',
    'howItWorks.legal.item1': '持牌印尼公证人',
    'howItWorks.legal.item2': '信誉良好的法律顾问',
    'howItWorks.legal.item3': '成熟的物业管理合作伙伴',
    'howItWorks.legal.docsIntro': '每一步都有记录，投资者会收到以下方面的清晰解释：',
    'howItWorks.legal.doc1': '所有权',
    'howItWorks.legal.doc2': '租赁条款',
    'howItWorks.legal.doc3': '付款时间表',
    'howItWorks.legal.doc4': '持续义务',
    'howItWorks.legal.closing': '我们的职责是确保您完全理解您购买的是什么以及它在实践中如何运作。',
    'howItWorks.faq.title': '常见问题',
    'howItWorks.faq.q1': '外国人可以在印尼合法拥有房产吗？',
    'howItWorks.faq.a1': '可以。虽然外国人不能持有永久产权土地，但租赁权和其他法律结构允许安全、长期地拥有和控制房产。',
    'howItWorks.faq.q2': '我可以转售我的房产吗？',
    'howItWorks.faq.a2': '可以。租赁权房产可以根据印尼法律和项目条款出售给其他买家、转让或分配。',
    'howItWorks.faq.q3': '我可以自己使用单位吗？',
    'howItWorks.faq.a3': '可以。业主可以根据项目规则和任何约定的租赁日历入住其房产。',
    'howItWorks.faq.q4': '租金收入如何支付？',
    'howItWorks.faq.a4': '收入通常按月或按季度分配，管理公司提供透明的运营报告。',
    'howItWorks.faq.q5': '如果法规发生变化怎么办？',
    'howItWorks.faq.a5': '印尼在支持旅游房产外国投资方面有着悠久而稳定的历史。Wahi以保守方式构建所有项目，以最大程度降低监管风险。',
    'howItWorks.risks.title': '需要了解的风险',
    'howItWorks.risks.description': '与任何国际投资一样，在印尼购买房产涉及以下考虑：',
    'howItWorks.risks.item1': '汇率波动',
    'howItWorks.risks.item2': '旅游市场周期',
    'howItWorks.risks.item3': '运营绩效',
    'howItWorks.risks.item4': '当地法规变化',
    'howItWorks.risks.closing': 'Wahi不承诺或保证回报。我们专注于保守规划、现实假设和专业执行，以创建具有韧性的长期资产。',
    'howItWorks.cta.title': '有问题吗？',
    'howItWorks.cta.description': '与Wahi代表交谈，讨论您的情况和目标。',
    'howItWorks.cta.button': '预约咨询',
    
    // Contact Page
    'contact.hero.title': '与Wahi本地代表交谈',
    'contact.hero.description': '如果您正在考虑在印尼投资，并希望进行结构化、透明的讨论，请与Wahi本地代表预约咨询。',
    'contact.form.title': '请求咨询',
    'contact.form.firstName': '名',
    'contact.form.lastName': '姓',
    'contact.form.email': '电子邮件地址',
    'contact.form.phone': '电话号码',
    'contact.form.country': '居住国家',
    'contact.form.budget': '投资预算范围',
    'contact.form.budgetPlaceholder': '例如，20万-50万美元',
    'contact.form.message': '留言',
    'contact.form.messagePlaceholder': '告诉我们您的投资兴趣和您的问题。',
    'contact.form.submit': '提交咨询',
    'contact.form.sending': '发送中...',
    'contact.form.disclaimer': '提交此表格即表示您同意Wahi代表与您联系。',
    'contact.form.success.title': '消息已发送',
    'contact.form.success.description': '我们将在24小时内与您联系。',
    'contact.expect.title': '期望什么',
    'contact.expect.call.title': '初次通话',
    'contact.expect.call.description': '30分钟的介绍性通话，了解您的投资目标并回答初步问题。',
    'contact.expect.presentation.title': '项目展示',
    'contact.expect.presentation.description': '详细展示相关项目，包括规格、定价和投资预测。',
    'contact.expect.structure.title': '结构讨论',
    'contact.expect.structure.description': '审查所有权结构、法律考虑和您所在司法管辖区的税务影响。',
    'contact.expect.noObligation.title': '无义务',
    'contact.expect.noObligation.description': '我们的咨询是信息性的，没有压力。请慢慢做出明智的决定。',
    'contact.rep.title': '您的本地代表',
    'contact.rep.name': '[代表姓名]',
    'contact.rep.role': 'Wahi区域代表',
    'contact.rep.photo': '照片',
  },
};

interface LanguageProviderProps {
  children: ReactNode;
}

export function LanguageProvider({ children }: LanguageProviderProps) {
  const [language, setLanguage] = useState<Language>(() => {
    if (typeof window !== 'undefined') {
      const saved = localStorage.getItem('wahi-language');
      if (saved && (saved === 'en' || saved === 'id' || saved === 'zh')) {
        return saved as Language;
      }
    }
    return 'en';
  });

  useEffect(() => {
    localStorage.setItem('wahi-language', language);
  }, [language]);

  const t = (key: string): string => {
    return translations[language][key] || translations['en'][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
